name: Deploy Docs to CF Workers
on:
  push:
    branches:
      - main
    paths:
      - apps/docs
      - "!apps/docs/AGENTS.md"
      - "!apps/docs/tsconfig.json"
      - .github/workflows/deploy-docs.yaml

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - name: Set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 22.18.0
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./apps/docs
          packageManager: pnpm
